### ISSUE TITLE
Tab coloring doesn't support browser restart!

### ISSUE THREAD

**Issue by collector-ynh** [emvaized/tst-colorize-tabs#8]
Hello, the extension is not working properly. It is possible to color the tabs, but when restarting the coloring of the tabs disappears or moves to other tabs!

tst-colorize-tabs is a very important and unique extension, but it's unusable as things stand. I'd love to see these bugs fixed.

**Comment by emvaized** [comment]
Sorry, I don't actively develop this extension right now, as I switched to another tree tabs extension. 

I would say, colors restoration on restart has always been problematic, and not sure – maybe over time TreeStyleTabs API was changed making it even worse. 

If someone with good knowledge of TST API could contribute and improve this, I'll happily accept their pull request and publish, but until then not sure how I could help you

**Comment by collector-ynh** [comment]
All right. Thank you for your reply!

Just out of curiosity, which tree tab extension are you using at the moment? And what are its advantages over TST?

**Comment by emvaized** [comment]
I'm using Sidebery V5 right now – it became much more stable and reliable over time, and also provides tab coloring functionality out the box

**Comment by collector-ynh** [comment]
I've tested Sidebery but can't find any function that lets you color tabs individually!

I've also tested the **tst_tab_favorites** extension which colors tabs well, the coloring remains in place even after the browser is restarted, but there's only one coloring and the extension doesn't work well when several windows are open. 

https://github.com/hannu40k/tst_tab_favorites

**Comment by emvaized** [comment]
The tab color functionality is only available in the newer v5 version of
Sidebery, which is not yet in the addons store and could be installed only
from its Github page. And then, you might need to visit the extension
settings and enable the coloring context menu entry manually, as I don't
remember if it's enabled by default.

пт, 16 июн. 2023 г. в 21:21, collector-ynh ***@***.***>:

**Comment by irvinm** [comment]
@emvaized ... have you ever tried to at least to log when the exception handler gets triggered in this code?  I had an issue with an addon I did with TST where my addon would come up very quickly and TST took 2-3 seconds before it was up.  I just ended up adding a sleep loop to keep trying to register with TST until it was successful before doing anything else and that solved my problem.  (250ms delays between tries)  I'm sure there is a more elegant way, but I am not a JS expert.

I haven't used this addon, but that might explain the "problematic" behavior.  (I saw the issue on the TST Github page)

https://github.com/emvaized/tst-colorize-tabs/blob/49dd318c3b6619944bc2a05fb602754f32c7ec35/background.js#L254-L273

**Comment by emvaized** [comment]
I guess problem most likely comes from the shaky logic of colors restoring on browser start. Since tabs don't have some reliable identifier, which is persistent through browser reboots, this extension relies on tab's saved index to reapply colors, and it adds listeners on tabs creation, removal and reorder to update saved indexes and corresponding colors. 

But the logic there is pretty basic, and probably fails in some use cases

**Comment by Nalla22** [comment]
@emvaized Hi, @irvinm managed to solve the extension problems with the following fork https://github.com/irvinm/TST-Colorize-Tabs

it would be nice to update the official repository with this working version

**Comment by emvaized** [comment]
@Nalla22 
Thanks, sounds promising! I can accept a PR from you to merge changes in the main tree — or you could publish it as a new addon yourself on Firefox addons, if you like (in this case please also create PR to add it to [the list](https://github.com/piroor/treestyletab#extensions-that-extend-tst)).

**Comment by emvaized** [comment]
Hi @irvinm,
I noticed that you have done a great job in your fork of TST-Colorize-Tabs, significantly improving functionality and stability. Since many users continue to download my extension and leave reviews about its poor performance, I would like to release an update fixing these issues. 

Please let me know what your future plans are for the development. I would like to accept pull requests with your changes and release an update. But considering the amount of changes you make, it also makes sense if you will willing to publish your own version in the Addons Store, and then I will liekly deprecate this addon in favor of yours and update the link in TST's Wiki page. 

Please let me know what suits you better!

**Comment by emvaized** [comment]
@irvinm 
I believe it makes more sense to merge your changes to the main repo and release an updated version of the extension on Firefox Addons store , so that all 598 users of the extension could benefit from your changes. Please let me know what you think of it, and if you are willing to continue supporting this extension.

**Comment by irvinm** [comment]
Hey @emvaized I think the real challenge here is that when I made these changes, I did have to make some fundamental changes to the addon and honestly I am not sure I covered all of the use cases and my branch hasn't likely had much usage.

https://github.com/irvinm/TST-Colorize-Tabs/blob/master/CHANGELOG.md

Obviously the biggest change was moving browser.storage.local.set\get to browser.sessions.getTabValue\setTabValue but that necessitated removing some code you were using to track indexing which was no longer needed.  It also introduced a limitation that if you closed a tab and restored it that the color information would not be retained.  Firefox treats restored tabs as basically new tabs and does not retain info set by get/setTabValue().

Additionally, I did add some things I was just playing around with:

- Keyboard shortcut support to traverse colorized tabs and options to stop at top/bottom or cycle around.
- Added badge count number for the number of colorized tabs
- Added a few options and allowed it support dark/light preferences

So ... I guess all of this to say is that my branch is a bit of a mix of different things and I am not sure you would want all of it.  I would really also recommend having some people try it out to ensure things are working as expected before releasing anything.

**Comment by emvaized** [comment]
I guess I never worked with `browser.sessions` API before. Does the `tabValue` persist between browser restarts? If yes, then it makes sense to use it instead of storing tab indexes. 

Keyboard shortcut support is also a great addition, as it was requested here in another issue! However, I can't find much usage for the icon badge in the context of this extension. Also, having a separate option for dark/light mode seems a bit excessive for me, considering that it is only applied on the Options page – I would've just preferred an automatic theme switching based on [prefers-color-scheme](https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme) CSS rule.

**Comment by emvaized** [comment]
@irvinm 
I guess I never worked with `browser.sessions` API before. Does the `tabValue` persist between browser restarts? If yes, then it makes sense to use it instead of storing tab indexes. 

Keyboard shortcut support is also a great addition, as it was requested here in another issue! However, I can't find much usage for the icon badge in the context of this extension. Also, having a separate option for dark/light mode seems a bit excessive for me, considering that it is only applied on the Options page – I would've just preferred an automatic theme switching based on [prefers-color-scheme](https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme) CSS rule.

**UPD**: I just tested your fork, and it seems to work just fine, tabs colors survive browser restart with no problem. I also noticed that the [red icon](https://github.com/emvaized/tst-colorize-tabs/blob/master/icons/red.svg) in my code has been tremendiously huge and broken all this time, bloated with some Adobe Illustrator tags, and no one even noticed! Now I feel a much greater urge to release an update and fix it.

**Comment by irvinm** [comment]
Yeah, I would say, take what you want from my code (or ideas) and incorporate as you want.  Working with "tabValue" is really easy and the browser handles everything for you across sessions.  (Just remember that if the tab is closed and then "restored" these values will not be there as it will get a new tab ID)

**Comment by emvaized** [comment]
> Just remember that if the tab is closed and then "restored" these values will not be there as it will get a new tab ID)

I wouldn't worry about that much, considering that my older version didn't restore tab color in this cases either :)

**Comment by emvaized** [comment]
I just published a `2.0.0` update including all contributions by @irvinm  🎉
I hope colors restoring will work fine from now on
